# Generated by Django 2.2.1 on 2019-07-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20190724_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
